experiment:
  name: ganomaly_test
  seed: 42

model:
  name: ganomaly
  params:
    encoder_design: configs/models/autoenc_encoder.yaml
    decoder_design: configs/models/autoenc_decoder.yaml

dataset:
  name: defect_images
  params:
    data_dir: ./data/defects
    batch_size: 16

optimizer:
  name: adam
  params:
    lr: 0.0002
    beta_1: 0.5
    
trainer:
  epochs: 50
  mixed_precision: False
  distributed: False
  diagnostics_interval: 5
  
run_overfit_test: True
diagnostics: True
