experiment:
  name: unet_focal_iou
model:
  name: unet
  params:
    input_shape: [256, 256, 3]
    num_classes: 1
loss:
  name: focal
optimizer:
  name: adam
  params:
    lr: 0.0001
trainer:
  epochs: 40
